# Generated by Django 5.1.5 on 2025-02-06 18:50

import candidate_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('year_of_birth', models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1974), candidate_app.models.max_value_current_year])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('LGBTQ', 'LGBTQ')], default='male', max_length=6)),
                ('payment_preference', models.CharField(choices=[('cash', 'Cash'), ('monthly', 'Monthly'), ('ok to all', 'Ok to All')], default='cash', max_length=9)),
                ('availabilities', models.TextField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
